import { Space_Grotesk } from "next/font/google"
import "@/styles/globals.css"
import NavBar from "@/components/NavBar"
import { AuthProvider } from "./Providers"
import AdminBar from "@/components/AdminBar"

const spaceGrotesk = Space_Grotesk({
    subsets: ["latin"],
    display: "swap",
    weight: ["500", "700"],
    style: ["normal"],
})

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({ children }) {
    return (
        <html lang="pl" className="dark">
            <body
                className={`${spaceGrotesk.className} bg-dark-bg text-light-text`}>
                <AuthProvider>
                    <AdminBar />
                    <NavBar />
                    {children}
                </AuthProvider>
            </body>
        </html>
    )
}
